import { Link } from "react-router-dom";
import { PageContainer, PageTitle, SectionTitle, Stack, Body, Muted } from "../components/ui/Layout";
import { LegalNotice } from "../components/ui/LegalNotice";
import { usePageMeta } from "../hooks/usePageMeta";
import { useBranding } from "../context/BrandingContext";

export const Privacy = () => {
  const { platformName } = useBranding();
  usePageMeta({
    title: "Privacy Policy",
    description: `How ${platformName} collects, uses, and protects your account, verification, and booking data.`,
  });

  return (
    <PageContainer>
      <Stack $gap={5}>
        <PageTitle>Privacy Policy</PageTitle>

        <LegalNotice>
          <strong>This is placeholder MVP content</strong> — it is not real legal text and has not
          been reviewed by a lawyer. Replace this page with a privacy policy reviewed by
          qualified legal counsel before taking {platformName} to a real launch, especially given
          the ID documents this app collects for verification.
        </LegalNotice>

        <Stack $gap={2}>
          <SectionTitle>1. Information we collect</SectionTitle>
          <Body>
            Account details you provide directly: email, name, mobile number (optional), city,
            and profile photo. Verification documents you submit for KYC: Aadhaar, PAN, a driving
            licence, business/GST certificate, or other supporting documents. Activity data
            generated by using the app: trips, booking requests, chat messages, ratings, and
            support requests.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>2. How we use your information</SectionTitle>
          <Body>
            We use this information to operate the marketplace — matching shippers with spare
            truck capacity, verifying identities before allowing bookings to be accepted, sending
            booking and account notifications, and providing customer support. We do not sell your
            personal information.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>3. Handling of verification (KYC) documents</SectionTitle>
          <Body>
            Identity documents you submit are used only to review and approve your verification
            status and are visible to our verification team. They are not shared with other users
            or third parties except as required by law.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>4. What other users can see</SectionTitle>
          <Body>
            When you have an active booking with someone, they can see your name, city, and
            rating — enough to coordinate a pickup — along with any chat messages you exchange.
            Your mobile number and verification documents are never shown to other users.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>5. Data retention</SectionTitle>
          <Body>
            We retain account and booking data for as long as your account is active, and for a
            reasonable period afterward to meet legal, accounting, or dispute-resolution needs.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>6. Your choices</SectionTitle>
          <Body>
            You can update your profile details, or choose which categories of notifications you
            receive, from your <Link to="/profile">Profile</Link> page at any time. To request
            deletion of your account or data, contact us via{" "}
            <Link to="/support">Support</Link>.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>7. Security</SectionTitle>
          <Body>
            We use reasonable technical and organizational measures to protect your information —
            verification documents are encrypted at rest, and account access is protected by
            one-time codes rather than a password alone unless you choose to set one. No system is
            completely secure, and we can't guarantee absolute security of data transmitted to or
            from the app.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>8. Children's privacy</SectionTitle>
          <Body>{platformName} is intended for users aged 18 and over and is not directed at children.</Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>9. Changes to this policy</SectionTitle>
          <Body>
            We may update this policy as the product evolves. Material changes will be reflected
            on this page.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>10. Contact us</SectionTitle>
          <Body>
            Questions about this policy or your data? Reach out via <Link to="/support">Support</Link>.
          </Body>
        </Stack>

        <Muted>Last updated: placeholder — set this when the page is replaced with reviewed legal text.</Muted>
      </Stack>
    </PageContainer>
  );
};

export default Privacy;
