import { Link } from "react-router-dom";
import { PageContainer, PageTitle, SectionTitle, Stack, Body, Muted } from "../components/ui/Layout";
import { LegalNotice } from "../components/ui/LegalNotice";
import { usePageMeta } from "../hooks/usePageMeta";
import { useBranding } from "../context/BrandingContext";

export const Privacy = () => {
  const { platformName } = useBranding();
  usePageMeta({
    title: "Privacy Policy",
    description: `How ${platformName} collects, uses, and protects your account, verification, and booking data.`,
  });

  return (
    <PageContainer>
      <Stack $gap={5}>
        <PageTitle>Privacy Policy</PageTitle>

        <LegalNotice>
          This page describes how {platformName} actually handles your data today, in plain
          language. It is published for transparency but has not yet received a final review by
          qualified legal counsel — especially given the identity documents this app collects for
          verification. Questions about your data are always welcome via{" "}
          <Link to="/support">Support</Link>.
        </LegalNotice>

        <Stack $gap={2}>
          <SectionTitle>1. Information we collect</SectionTitle>
          <Body>
            Account information you provide directly: name, email, mobile number (optional), city,
            and profile photo. Verification documents you submit for KYC: Aadhaar, PAN, a driving
            licence, a business/GST certificate, or other supporting documents. Shipment and booking
            details: pickup and drop information, shipment description and weight, and communication
            records. Activity data generated by using the app: trips, booking requests, chat
            messages, ratings, and support requests. Technical/device information necessary to
            operate and secure the platform.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>2. How we use your information</SectionTitle>
          <Body>
            We use this information to create and manage your account; match shipments with
            available capacity; facilitate booking requests; verify identities before allowing
            bookings to be accepted; communicate with you about your account and bookings; provide
            customer support; prevent fraud and misuse; improve platform performance; maintain
            records; and comply with legal obligations. We do not sell your personal information.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>3. Handling of verification (KYC) documents</SectionTitle>
          <Body>
            Identity documents you submit are used only to review and approve your verification
            status and are visible to our verification team. They are encrypted at rest and are not
            shared with other users or third parties except as required by law.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>4. What other users can see</SectionTitle>
          <Body>
            When you have an active booking with someone, they can see your name, city, and rating —
            enough to coordinate a pickup — along with any chat messages you exchange. Your mobile
            number and verification documents are never shown to other users.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>5. Location information</SectionTitle>
          <Body>
            When you search a route or enter a pickup/drop address, we use location data — through
            our mapping provider — to power address autocomplete and route matching. We don't
            continuously track your device's location in the background; location is only processed
            when you actively use a location feature such as the search or booking forms.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>6. Sharing of information</SectionTitle>
          <Body>
            Relevant information may be shared with the other party to a booking where necessary to
            facilitate it (see "What other users can see" above), with service providers that support
            the platform (such as hosting, email/SMS delivery, and mapping), and with authorities
            where required by law. We don't disclose more information than is reasonably necessary
            for the relevant purpose.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>7. Communications</SectionTitle>
          <Body>
            We send service-related communications such as booking updates, account notices,
            security alerts, and support messages. You can choose which categories of these
            notifications you receive from your <Link to="/profile">Profile</Link> page at any time.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>8. Data security</SectionTitle>
          <Body>
            We use reasonable technical and organizational measures to protect your information —
            verification documents are encrypted at rest, and account access is protected by
            one-time codes rather than a password alone unless you choose to set one. No system is
            completely secure, and we can't guarantee absolute security of data transmitted to or
            from the app.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>9. Data retention</SectionTitle>
          <Body>
            We retain account and booking data for as long as your account is active, and for a
            reasonable period afterward to meet contractual, accounting, dispute-resolution, fraud
            prevention, and other legal obligations.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>10. Your choices & rights</SectionTitle>
          <Body>
            You can access and update your profile details, or change your notification preferences,
            from your <Link to="/profile">Profile</Link> page at any time. To request access,
            correction, or deletion of your account or data, contact us via{" "}
            <Link to="/support">Support</Link> — subject to any legitimate retention requirements
            described above.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>11. Children's privacy</SectionTitle>
          <Body>{platformName} is intended for users aged 18 and over and is not directed at children.</Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>12. Changes to this policy</SectionTitle>
          <Body>
            We may update this policy as the product evolves. Material changes will be reflected on
            this page.
          </Body>
        </Stack>

        <Stack $gap={2}>
          <SectionTitle>13. Contact us</SectionTitle>
          <Body>
            Questions about this policy or your data? Reach out via{" "}
            <Link to="/support">Support</Link>.
          </Body>
        </Stack>

        <Muted>Last updated: 17 August 2026</Muted>
      </Stack>
    </PageContainer>
  );
};

export default Privacy;
