import styled from "styled-components";
import { Link } from "react-router-dom";
import { PageContainer, PageTitle, SectionTitle, Stack, Muted } from "../components/ui/Layout";

// Placeholder-content warning banner — same treatment on Terms.jsx, kept
// local to each file rather than shared since it's the only place it's used.
const Notice = styled.div`
  border: 1px solid ${({ theme }) => theme.color.warning};
  background: ${({ theme }) => theme.color.warningSoft};
  border-radius: ${({ theme }) => theme.radius.md};
  padding: ${({ theme }) => theme.space(4)};
  color: ${({ theme }) => theme.color.text};
  font-size: 14px;
  line-height: 1.5;
`;

export const Privacy = () => (
  <PageContainer>
    <Stack $gap={5}>
      <PageTitle>Privacy Policy</PageTitle>

      <Notice>
        <strong>This is placeholder MVP content</strong> — it is not real legal text and has not
        been reviewed by a lawyer. Replace this page with a privacy policy reviewed by qualified
        legal counsel before taking ShareTruck to a real launch, especially given the ID
        documents this app collects for verification.
      </Notice>

      <Stack $gap={2}>
        <SectionTitle>1. Information we collect</SectionTitle>
        <Muted>
          Account details you provide directly: mobile number, name, email, city, and profile
          photo. Verification documents you submit for KYC: Aadhaar, PAN, driving licence,
          business/GST certificate, or other supporting documents. Activity data generated by
          using the app: trips, booking requests, chat messages, ratings, and support requests.
        </Muted>
      </Stack>

      <Stack $gap={2}>
        <SectionTitle>2. How we use your information</SectionTitle>
        <Muted>
          We use this information to operate the marketplace — matching shippers with spare
          truck capacity, verifying identities before allowing bookings to be accepted, sending
          booking and account notifications, and providing customer support. We do not sell your
          personal information.
        </Muted>
      </Stack>

      <Stack $gap={2}>
        <SectionTitle>3. Handling of verification (KYC) documents</SectionTitle>
        <Muted>
          Identity documents you submit are used only to review and approve your verification
          status and are visible to our verification team. They are not shared with other users
          or third parties except as required by law.
        </Muted>
      </Stack>

      <Stack $gap={2}>
        <SectionTitle>4. What other users can see</SectionTitle>
        <Muted>
          When you have an active booking with someone, they can see your name, city, and rating
          — enough to coordinate a pickup — along with any chat messages you exchange. Your
          mobile number and verification documents are never shown to other users.
        </Muted>
      </Stack>

      <Stack $gap={2}>
        <SectionTitle>5. Data retention</SectionTitle>
        <Muted>
          We retain account and booking data for as long as your account is active, and for a
          reasonable period afterward to meet legal, accounting, or dispute-resolution needs.
        </Muted>
      </Stack>

      <Stack $gap={2}>
        <SectionTitle>6. Your choices</SectionTitle>
        <Muted>
          You can update your profile details, or choose which categories of notifications you
          receive, from your <Link to="/profile">Profile</Link> page at any time. To request
          deletion of your account or data, contact us via{" "}
          <Link to="/support">Support</Link>.
        </Muted>
      </Stack>

      <Stack $gap={2}>
        <SectionTitle>7. Security</SectionTitle>
        <Muted>
          We use reasonable technical and organizational measures to protect your information.
          No system is completely secure, and we can't guarantee absolute security of data
          transmitted to or from the app.
        </Muted>
      </Stack>

      <Stack $gap={2}>
        <SectionTitle>8. Children's privacy</SectionTitle>
        <Muted>ShareTruck is intended for users aged 18 and over and is not directed at children.</Muted>
      </Stack>

      <Stack $gap={2}>
        <SectionTitle>9. Changes to this policy</SectionTitle>
        <Muted>
          We may update this policy as the product evolves. Material changes will be reflected
          on this page.
        </Muted>
      </Stack>

      <Stack $gap={2}>
        <SectionTitle>10. Contact us</SectionTitle>
        <Muted>
          Questions about this policy or your data? Reach out via <Link to="/support">Support</Link>.
        </Muted>
      </Stack>

      <Muted>Last updated: placeholder — set this when the page is replaced with reviewed legal text.</Muted>
    </Stack>
  </PageContainer>
);

export default Privacy;
